#!/bin/sh

set -e

if [ "$#" -ne 2 ]; then
	printf '%s\n' "usage: mkuser <username> <ssh_key>"
	exit 1
fi

adduser --disabled-password --comment '' -- "$1"
SSH_KEY="$2" runuser -- "$1" <<-'EOF'
	set -e

	mkdir -m 0700 ~/.ssh
	touch ~/.ssh/authorized_keys
	chmod 0600 ~/.ssh/authorized_keys
	printf '%s\n' "$SSH_KEY" > ~/.ssh/authorized_keys
EOF
